### create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "gyurt32@gmail.com",
  "password": "12345678"
}

### find user
GET http://localhost:3000/auth/2

### find all users
GET http://localhost:3000/auth?email=gyurt32413@gmail.com

### delete user
DELETE http://localhost:3000/auth/1

### update user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "email": "gy@gmail.com"
}