### create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "gyurt32@gmail.com",
  "password": "12345678"
}

### sign in
// cookie 只有在更新的時候才會顯示在請求結果
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "gyurt32@gmail.com",
  "password": "12345678"
}

### who am I
GET http://localhost:3000/auth/whoami

### sign out
POST http://localhost:3000/auth/signout

### find user
GET http://localhost:3000/auth/2

### find all users
GET http://localhost:3000/auth?email=gyurt32413@gmail.com

### delete user
DELETE http://localhost:3000/auth/1

### update user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "email": "gy@gmail.com"
}

### 測試
GET http://localhost:3000/auth/colors/blue222

### 測試
GET http://localhost:3000/auth/colors